"""Dashboard copy of the bot's command guide (Streamlit markdown format).

This is the markdown variant rendered in the dashboard's Alert Settings tab;
the Telegram-HTML variant lives in corporate_actions/bot/help_texts.py.
"""
HELP_TEXT = (
    "\U0001F4CA **Royal Stock — Command Guide**\n"
    "_Real-time NSE/BSE corporate actions, market movers & news_\n\n"
    "Every command name explains what it does. The old short forms still work\n"
    "as aliases (e.g. `/ca` = `/corpactions`, `/next` = `/corpactionsformylist`).\n\n"
    "**Corporate Actions (NSE + BSE)**\n"
    "- `/corpactions [TYPE | SYMBOL | N | today]` — browse all dividend / bonus / split / rights / buyback actions. `dividend`/`bonus`/`split`/`rights`/`buyback` = one type; `increase` = shareholder increase (bonus + split + rights); `today`/`N` = ex-date window; a symbol (e.g. `RELIANCE`) = full details; any other word = keyword search\n"
    "- `/exdates [today|N]` — all actions by ex-date window (default 5 days)\n"
    "- `/corpactionssummary` — corporate-action snapshot: counts by exchange & type, plus the next ex-dates\n"
    "- `/corpactionsformylist` — YOUR watchlist: upcoming ex-dates + recently passed / in-progress actions with status (rights subscription, dividend payment, bonus credit) — last 30 days\n\n"
    "**Watchlist**\n"
    "- `/watchlist` — show your full watchlist\n"
    "- `/myfavourites` — run your favourite commands in one go (corp actions for your list, top losers 1h + today, watchlist, fundamentals)\n"
    "- `/addstock SYMBOL [NSE|BSE]` — add a stock (default NSE)\n"
    "- `/removestock SYMBOL` — remove a stock\n"
    "- `/news [N|SYMBOL]` — latest headlines for your watchlist stocks\n\n"
    "**Stock Analysis**\n"
    "- Type in any symbol box and a live pick-list of matching tickers (symbol + full name + exchange) appears — pick from it instead of typing the whole code. Works in Fundamental Analysis, Watchlist add, News and Corporate Actions\n"
    "- `/fundamentalanalyze SYMBOL` — quick analysis card (price, P/E, 52W signal, RSI, MACD, SMA 50/200, QoQ holding)\n"
    "- `/fundamentalanalyze mylist` / `N` / `N-M` — same card for your watchlist (10 per page, Next button)\n"
    "- `/fundamentalreport SYMBOL` — DEEP fundamental report (valuation, growth, margins, balance sheet, EPS, analyst targets + a 📈 Technical Indicators block: RSI(14), MACD(12,26,9) line/signal/histogram with crossover, SMA 50/200 vs price) — much more detailed than `/fundamentalanalyze`\n"
    "- `/fundamentalreport mylist` / `N` / `N-M` — deep reports for your watchlist (5 per page)\n"
    "- `/harmonicpatterns [all|100|500] [TIMEFRAME]` — harmonic pattern scan & PRZ reports (alias `/harmonic`)\n"
    "- `/scan500` — full NIFTY 500 CNC/MIS technical scanner\n"
    "- Typed a wrong symbol? You get a pick-list of similar NSE tickers with company names\n\n"
    "**US Stocks (NASDAQ/NYSE)**\n"
    "- `/usstock TICKER` — live price + deep fundamentals for US stocks (AAPL, MSFT, BRK-B, BF.B) in USD — P/E, D/E, margins, ROE/ROCE, analyst targets, RSI, MACD & SMA 50/200 & more\n"
    "- Aliases: `/usfund`, `/usquote`, `/us`\n"
    "- Unknown ticker? You get a pick-list of similar US tickers with full company names (e.g. `/usstock spacex` → SPCX)\n"
    "- Schedule it: `/schedule add 3h /usstock AAPL us` — runs every 3h during US market hours\n\n"
    "**Market Screens**\n"
    "- `/topmovers [period|DATE] [N] [100|500]` — top gainers AND losers in a window\n"
    "- `/topgainers [period|DATE] [N] [100|500]` — top rising stocks\n"
    "- `/toplosers [period|DATE] [N] [100|500]` — top falling stocks\n"
    "  A DATE (12-08-2026 · 12 Aug · 12aug · 2026-08-12) switches any movers screen to that day's HISTORICAL movers (close vs previous close), e.g. `/toplosers 12-08-2026`.\n"
    "  Periods: 5m · 15m · 30m · 1h · 2h · 4h · today · 1d · 2d · 5d · 1w · 2w · 1mo · 3mo · 6mo · 1y\n"
    "  Universe: n100/nifty100 = NIFTY 100 · n500/nifty500 = NIFTY 500 · sp500 = S&P 500\n"
    "  Tip: for `/topgainers` & `/toplosers` a bare 100/500 means the top-N count (e.g. `/topgainers 100` = top 100) — use `nifty100`/`nifty500` for the index. For `/topmovers` a bare 100/500 picks the index.\n"
    "- `/gappers [1d|2d|3d|window Nd|DATE|DATE DATE] [up|down|all] [N] [100|500|sp500]` — overnight gap scanner (prev close → open), default = gap-DOWNs only. `/gappers 1d`/`2d`/`3d` = gaps N sessions ago; `/gappers window 3d` = today's open vs the close 3 sessions ago; `/gappers 12-08-2026` = gaps that opened on that date; `/gappers 08-08-2026 12-08-2026` = cumulative gap over a period; `/gappers GODREJCP` = a stock's gap history.\n"
    "- `/moversover [%] [100|500|sp500]` — EVERY stock that moved over a % today in one list (like the watcher, but a full report; alias /bigmovers). `/moversover` = ≥5% today, NIFTY 500; `/moversover 8 sp500` = S&P 500. Runs from market open until the end of the session day (IST for NIFTY, ET for US) - after-hours runs still return the last session's moves.\n\n"
    "**Alerts & Personalisation**\n"
    "- `/alertfilters TYPE,TYPE` — receive only the action types you choose (`all` resets)\n"
    "- `/pricealert PCT` — alert when a stock moves ±PCT% in a day (`off` disables)\n"
    "- `/settings` — view your current filter & alert config\n\n"
    "**System**\n"
    "- `/status` — where your watchlist is saved & GitHub push status\n"
    "- `/schedule add 3h /scan500` — run a command automatically every 3h; `/schedule add at 09:15 /toplosers 1h` — daily at a clock time (works for every user; each person's reports go to their own chat)\n"
    "- `/schedule add at 09:15,15:30 /toplosers 1h` — daily at BOTH times = start + end results (open & close); a run window `from HH:MM to HH:MM` also always fires at its start AND end; interval entries (every X) fire exactly on the hour plus once more at session close (15:30 IST / 16:00 ET), while chosen clock times fire only at those times\n"
    "- `/schedule add 3h /cmd in|us|any` — run only during Indian / US market hours (`in` = NSE/BSE 09:15-15:30 IST, `us` = NASDAQ/NYSE 09:30-16:00 ET, `any` = always)\n"
    "- `/schedule pause 1d | 2d | 3d | 1w | 2w | 1mo` — pause YOUR schedule (auto-resumes when it lapses; resume early with `/schedule resume`)\n"
    "- `/checknow` — force-run alerts and re-send all matches\n"
    "- `/watcher on` / `off` — sudden-move alerts; `set 5` = 5%, `universe nifty500` = nifty100/nifty500/mylist\n"
    "- `/menu` — one-tap command buttons in Telegram (no typing)\n"
    "- `/help` · `/start` — show this guide\n\n"
    "_Old short forms still work as aliases: /ca, /next, /upcoming, /summary, /add, /list, /movers, /gainers, /losers, /stock, /stockanalysis, /fund, /fundamentals, /filter, /alert, /sched, /exdate, /harmonic._\n"
)
