"""Static help and menu texts shown by the bot (/help, /all, /menu)."""

HELP_TEXT = (
    "\U0001F4CA <b>Stock Alert Bot \u2014 Command Guide</b>\n"
    "<i>Real-time NSE/BSE corporate actions, market movers &amp; news</i>\n\n"
    "Every command name explains what it does. The old short forms still work\n"
    "as aliases (e.g. <code>/ca</code> = <code>/corpactions</code>, "
    "<code>/next</code> = <code>/corpactionsformylist</code>).\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\U0001F3A8 <b>Colour &amp; Signal Legend</b>\n"
    "\U0001F7E2\u25b2 Green + Up arrow = Stock gaining\n"
    "\U0001F534\u25bc Red + Down arrow  = Stock falling\n"
    "\u2705 <b>Strong Buy</b> = Near 52-week LOW (\u226415% from bottom)\n"
    "\U0001F4C8 <b>Buy Zone</b>  = Low zone (15\u201335% from bottom)\n"
    "\U0001F7E1 <b>Mid-Range</b> = Middle of 52-week range\n"
    "\u26a0\ufe0f <b>High Zone</b>  = Near 52-week HIGH (65\u201385%)\n"
    "\U0001F6AB <b>Avoid</b>     = At/near 52-week HIGH (\u226585%)\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\U0001F4C5 <b>Corporate Actions (NSE + BSE)</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/corpactions <i>[TYPE | SYMBOL | N | today]</i>\n"
    "  Browse all dividend / bonus / split / rights / buyback actions.\n"
    "  /corpactions                  \u2192 overview of everything upcoming\n"
    "  /corpactions dividend         \u2192 only dividend announcements\n"
    "  /corpactions bonus|split|rights|buyback  \u2192 one action type\n"
    "  /corpactions increase         \u2192 shareholder increase (bonus+split+rights)\n"
    "  /corpactions today            \u2192 ex-dates due today\n"
    "  /corpactions 7                \u2192 ex-dates within the next 7 days\n"
    "  /corpactions RELIANCE         \u2192 full details for one symbol\n"
    "  /corpactions TATA             \u2192 keyword search (company/subject)\n\n"
    "/exdates <i>[today|N]</i>       \u2192 all actions by ex-date window\n"
    "  (default 5 days) \u00b7  /exdates today  \u00b7  /exdates 10\n\n"
    "/corpactionssummary  \u2192 corporate-action snapshot: counts by exchange\n"
    "                       &amp; type, plus the next ex-dates\n\n"
    "/corpactionsformylist \u2192 YOUR watchlist: upcoming ex-dates PLUS recently\n"
    "                       passed / in-progress actions with status (rights\n"
    "                       subscription open, dividend payment due/pending,\n"
    "                       bonus credit) \u2014 last 30 days\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\u2B50 <b>Watchlist</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/watchlist           \u2192 show your full watchlist\n"
    "/myfavourites        \u2192 see / run / edit your favourite commands:\n"
    "                       <code>/myfavourites run</code> fires them all now\n"
    "/addstock SYMBOL [NSE|BSE] \u2192 add a stock (default NSE)\n"
    "  /addstock RELIANCE NSE  \u00b7  /addstock PGINVIT\n"
    "/removestock SYMBOL  \u2192 remove a stock from your watchlist\n"
    "  /removestock TCS\n"
    "/news <i>[N|SYMBOL]</i> \u2192 latest headlines for your watchlist stocks\n"
    "  /news              \u2192 news for all watchlist stocks\n"
    "  /news 5            \u2192 5 headlines per stock\n"
    "  /news RELIANCE     \u2192 news for RELIANCE only\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\U0001F50D <b>Stock Analysis</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/fundamentalanalyze <i>SYMBOL</i>  \u2192 quick analysis card\n"
    "  /fundamentalanalyze TATATECH  \u2192 price, P/E, 52W signal, QoQ shareholding\n"
    "/fundamentalanalyze <i>N | N-M | mylist</i>  \u2192 same card for your stocks\n"
    "  /fundamentalanalyze mylist  \u2192 your whole watchlist (10 per page, Next button)\n"
    "  /fundamentalanalyze 5-10    \u2192 watchlist stocks #5 to #10\n\n"
    "/fundamentalreport <i>SYMBOL</i>  \u2192 DEEP fundamental report\n"
    "  (much more detailed than /fundamentalanalyze)\n"
    "  /fundamentalreport RELIANCE  \u2192 valuation, growth, margins, balance sheet,\n"
    "                     EPS, analyst targets &amp; shareholding\n"
    "  /fundamentalreport 3-5   \u2192 deep report for watchlist #3..#5\n"
    "  /fundamentalreport mylist \u2192 deep report for your whole watchlist (5 per page)\n\n"
    "/checklist <i>SYMBOL</i>  \u2192 32-point investment scorecard\n"
    "  10 personal + 22 AI criteria checked &amp; scored (D/E, ROE, ROCE, margins,\n"
    "  FCF, PEG, P/FCF, EV/EBITDA, P/E vs sector...).\n"
    "  /checklist RELIANCE  \u2192 one stock \u00b7  /checklist mylist \u00b7  /checklist 5-10\n"
    "  (alias /investcheck, /scorecard)\n\n"
    "/harmonicpatterns <i>[all|100|500] [TIMEFRAME]</i>  \u2192 harmonic patterns\n"
    "  Scans for Gartley / Bat / Butterfly / Crab / Shark setups.\n"
    "  /harmonicpatterns all  \u2192 NIFTY 100, daily \u00b7  /harmonicpatterns 500 1w\n"
    "  /harmonicpatterns RELIANCE  \u2192 full report with PRZ, entry, SL &amp; targets\n"
    "  Timeframes: 5m 15m 30m 1h 4h 1d 1w (alias /harmonic)\n\n"
    "/scan500             \u2192 full NIFTY 500 CNC/MIS technical scanner\n"
    "  EMAs, RSI, MACD, ADX, CMF, OBV, Aroon, TTM Squeeze, Supertrend, GMMA,\n"
    "  VWAP &amp; Mansfield RS \u2014 scores survivors /100, picks the #1 setup and\n"
    "  maps an hour-by-hour CNC vs MIS execution plan (takes ~1-2 min).\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\U0001F4C8 <b>Market Screens</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/topmovers <i>[period] [N] [100|500]</i>  \u2192 top gainers AND losers\n"
    "  /topmovers          \u2192 last 1h, NIFTY 100\n"
    "  /topmovers 2d 500   \u2192 2-day movers, NIFTY 500\n"
    "  /topmovers 1w 10    \u2192 top 10 movers this week\n\n"
    "/topgainers <i>[period] [N] [100|500]</i>  \u2192 top rising stocks\n"
    "  /topgainers 1h          \u2192 last 1h gainers\n"
    "  /topgainers 1mo 20 500  \u2192 top 20 gainers this month, NIFTY 500\n\n"
    "/toplosers <i>[period] [N] [100|500]</i>  \u2192 top falling stocks\n"
    "  Tap any line below to copy the command:\n"
    "  <code>/toplosers</code>              \u2192 today\u2019s top 30 losers\n"
    "  <code>/toplosers 1h 10</code>        \u2192 top 10 losers last hour\n"
    "  <code>/toplosers 100</code>          \u2192 top 100 losers today\n"
    "  <code>/toplosers 1w nifty100</code>  \u2192 weekly losers, NIFTY 100\n"
    "  <code>/toplosers 20 500</code>       \u2192 top 20 losers, NIFTY 500\n"
    "  <code>/toplosers 30m</code>          \u2192 last 30 minutes\n"
    "  Type /toplosers alone for the full copy-paste guide.\n"
    "  Movers reports end with a <b>Get Fundamentals</b> button - tap it for\n"
    "  P/E, ROCE/ROE, dividend yield etc. Change this with /moversfund.\n\n"
    "Periods: 5m \u00b7 15m \u00b7 30m \u00b7 1h \u00b7 2h \u00b7 4h \u00b7 today \u00b7 1d \u00b7 2d \u00b7 5d \u00b7 1w \u00b7 2w \u00b7 1mo \u00b7 3mo \u00b7 6mo \u00b7 1y\n"
    "Universe: n100/nifty100=NIFTY 100 \u00b7 n500/nifty500=NIFTY 500\n"
    "Tip: for /topgainers &amp; /toplosers a bare 100/500 means the top-N count\n"
    "(e.g. /topgainers 100 = top 100) - use nifty100/nifty500 or a second\n"
    "number for the index. For /topmovers a bare 100/500 picks the index.\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\u2699\ufe0f <b>Alerts &amp; Personalisation</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/alertfilters TYPE,TYPE  \u2192 receive only the action types you choose\n"
    "  /alertfilters dividend,bonus  \u00b7  /alertfilters all (reset)\n"
    "  Types: dividend \u00b7 bonus \u00b7 split \u00b7 rights \u00b7 buyback\n"
    "/pricealert PCT      \u2192 alert when a stock moves \u00b1PCT% in a day\n"
    "  /pricealert 3      \u2192 alert on \u00b13% move  \u00b7  /pricealert off (disable)\n"
    "/settings            \u2192 view your current filter &amp; alert config\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\U0001F6E0 <b>System</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/status              \u2192 YOUR personal setup (watchlist, schedule, settings, alerts)\n"
    "/schedule add 3h /scan500  \u2192 YOUR report runs /scan500 automatically every 3h\n"
    "  (runs only while the Indian market is open by default - add <code>us</code> for US hours,\n"
    "   <code>any</code> to disable, or <code>from HH:MM to HH:MM</code> for a custom window)\n"
    "/schedule pause 1d \u00b7 3d \u00b7 1w \u00b7 2w \u00b7 1mo  \u2192 pause YOUR schedule\n"
    "/schedule resume          \u2192 resume early  \u00b7  /market us|in|any  \u2192 default gate\n"
    "/schedule run \u00b7 /schednow  \u2192 run all YOUR scheduled reports right now\n"
    "/checknow            \u2192 force-run alerts and re-send all matches\n"
    "/watcher             \u2192 big-move alerts: /watcher on, off, set 5, universe nifty500\n"
    "/moversfund          \u2192 movers: fundamentals via button or automatically\n"
    "/menu                \u2192 one-tap command buttons (tap, no typing)\n"
    "/all                 \u2192 every command in one copyable list\n"
    "/help \u00b7 /start       \u2192 show this guide\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\U0001F4A1 <b>Quick Examples</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/topgainers 1h 10          \u2192 Top 10 gainers last hour\n"
    "/toplosers 1mo nifty500   \u2192 Monthly losers \u2014 NIFTY 500\n"
    "/topmovers 2d 10 500       \u2192 2-day movers, top 10, NIFTY 500\n"
    "/scan500               \u2192 full NIFTY 500 CNC/MIS technical scan\n"
    "/corpactions dividend   \u2192 Upcoming dividends\n"
    "/corpactions RELIANCE   \u2192 RELIANCE corporate actions\n"
    "/corpactionsformylist  \u2192 Watchlist ex-dates + in-progress actions\n"
    "/myfavourites run        \u2192 All your regular commands in one go\n"
    "/addstock INFY NSE      \u2192 Add INFY to watchlist\n"
    "/news RELIANCE          \u2192 Latest RELIANCE headlines\n"
    "/alertfilters bonus,split  \u2192 Only bonus &amp; split alerts\n"
    "/pricealert 2.5         \u2192 Alert on \u00b12.5% daily move\n"
    "\U0001F4DD Type in plain text: \"gainers\", \"dividends\", \"ex-date today\", \"news\""
)

CA_HELP = (
    "Corporate Action queries (/corpactions, alias /ca):\n"
    "/corpactions - overview of all NSE + BSE actions\n"
    "/corpactions dividend | bonus | split | rights | buyback - one action type\n"
    "/corpactions increase - shareholder increase (bonus + split + rights)\n"
    "/corpactions today - ex-date today\n"
    "/corpactions 7 - ex-date within 7 days\n"
    "/corpactions RELIANCE - details for one symbol\n"
    "/corpactions TATA - keyword search in company name / subject"
)

QUICK_MENU_TEXT = (
    "<b>\U0001F447 One-Tap Command Menu</b>\n"
    "Tap any button below - the command runs instantly, no typing needed.\n\n"
    "\u2022 <code>/corpactionsformylist</code> - corporate actions for YOUR list\n"
    "\u2022 <code>/myfavourites run</code> - all your regular commands in one go\n"
    "\u2022 <code>/corpactions</code> - all NSE+BSE corporate actions\n"
    "\u2022 <code>/corpactionssummary</code> - counts + next ex-dates\n"
    "\u2022 <code>/topgainers 1h</code> / <code>/toplosers 1h</code> - movers\n"
    "\u2022 <code>/watchlist</code> - your stocks\n"
    "\u2022 <code>/all</code> - copy the full list of every command\n\n"
    "The menu stays visible until you hide it with <code>/menu off</code>."
)

ALL_COMMANDS_TEXT = (
    "<b>\U0001F4DA All Commands - copy any line and send it</b>\n"
    "<i>Every command you can use, grouped by purpose.</i>\n\n"
    "\u2B50 <b>One-Tap Menu</b>\n"
    "  /menu                    \u2192 show the button menu (always on until /menu off)\n"
    "  /menu off                \u2192 hide the button menu\n"
    "  /all                     \u2192 this list, always up to date\n\n"
    "\U0001F4C5 <b>Corporate Actions</b>\n"
    "  /corpactionsformylist    \u2192 corporate actions for YOUR watchlist\n"
    "  /corpactions             \u2192 all NSE+BSE corporate actions\n"
    "  /corpactionssummary      \u2192 counts + next ex-dates\n"
    "  /corpactions dividend    \u2192 only dividends\n"
    "  /corpactions bonus|split|rights|buyback \u2192 one type\n"
    "  /corpactions today       \u2192 ex-dates due today\n"
    "  /corpactions 7           \u2192 ex-dates in the next 7 days\n"
    "  /corpactions RELIANCE    \u2192 full details for one symbol\n"
    "  /corpactions TATA        \u2192 keyword search\n"
    "  /exdates [today|N]       \u2192 all actions by ex-date window\n\n"
    "\u2B50 <b>Watchlist &amp; Favourites</b>\n"
    "  /watchlist               \u2192 show your watchlist\n"
    "  /myfavourites            \u2192 see the commands it runs\n"
    "  /myfavourites run        \u2192 run your favourite commands\n"
    "  /myfavourites set /cmd   \u2192 replace your favourite commands\n"
    "  /myfavourites add /cmd   \u2192 append a command\n"
    "  /myfavourites remove N   \u2192 remove command #N\n"
    "  /myfavourites reset      \u2192 restore the default list\n"
    "  /addstock SYMBOL NSE|BSE \u2192 add a stock\n"
    "  /removestock SYMBOL      \u2192 remove a stock\n"
    "  /news [N|SYMBOL]         \u2192 headlines for your stocks\n\n"
    "\U0001F50D <b>Stock Analysis</b>\n"
    "  /fundamentalanalyze SYM  \u2192 quick analysis card\n"
    "  /fundamentalanalyze mylist | N-M \u2192 your stocks\n"
    "  /fundamentalreport SYM   \u2192 DEEP fundamental report\n"
    "  /fundamentalreport mylist|N-M \u2192 deep reports for your stocks\n"
    "  /checklist SYM           \u2192 32-point investment scorecard (10 personal + 22 AI)\n"
    "  /checklist mylist | N-M  \u2192 scorecards for your stocks\n"
    "  /harmonicpatterns [100|500] [TF] \u2192 harmonic scan\n"
    "  /scan500                 \u2192 full NIFTY 500 technical scanner\n\n"
    "\U0001F4C8 <b>Market Screens</b>\n"
    "  /topmovers [period] [N] [100|500]  \u2192 gainers AND losers\n"
    "  /topgainers [period] [N] [100|500] \u2192 top rising stocks\n"
    "  /toplosers [period] [N] [100|500]  \u2192 top falling stocks\n"
    "  Copy-ready examples (tap to copy):\n"
    "    <code>/toplosers</code> \u00b7 <code>/toplosers 1h 10</code> \u00b7 "
    "<code>/toplosers 100</code>\n"
    "    <code>/toplosers 1w nifty100</code> \u00b7 <code>/toplosers 20 500</code>\n"
    "  Periods: 5m 15m 30m 1h 2h 4h today 1d 2d 5d 1w 2w 1mo 3mo 6mo 1y\n"
    "  Universe: n100/nifty100 \u00b7 n500/nifty500\n\n"
    "\u2699\ufe0f <b>Alerts &amp; Personalisation</b>\n"
    "  /alertfilters TYPE,TYPE  \u2192 only chosen action types (dividend,bonus,split,rights,buyback)\n"
    "  /pricealert PCT          \u2192 alert on \u00b1PCT% daily move (off to disable)\n"
    "  /watcher on|off|set N|universe U \u2192 big-move alerts\n"
    "  /moversfund button|auto  \u2192 movers reports: fundamentals via button or auto\n"
    "  /settings                \u2192 view your filters, alerts &amp; screen options\n\n"
    "\U0001F6E0 <b>Automation</b>\n"
    "  /schedule                \u2192 show YOUR schedule\n"
    "  /schedule add 3h /scan500 \u2192 run every 3h\n"
    "  /schedule add at 09:15 /toplosers 1h \u2192 run daily at 09:15 IST\n"
    "  /schedule add 3h /scan500 us \u2192 only during US market hours\n"
    "  /schedule add 3h /scan500 any \u2192 no gate - run any time\n"
    "  /schedule add 3h /cmd in from 09:15 to 15:30 \u2192 custom run window\n"
    "  /schedule pause 1d|2d|3d|1w|2w|1mo \u2192 pause YOUR schedule (auto-resumes)\n"
    "  /schedule resume        \u2192 resume early\n"
    "  /market in|us|any       \u2192 YOUR default market-hours gate\n"
    "  /schedule run           \u2192 run all your scheduled commands NOW\n"
    "  /schednow                \u2192 alias of /schedule run\n"
    "  /schedule remove N       \u2192 remove entry #N\n"
    "  /schedule clear          \u2192 remove all of yours\n"
    "  /checknow                \u2192 force-run alert checks now\n"
    "  /status                  \u2192 your personal setup + GitHub push status\n\n"
    "\U0001F4A1 <b>Quick Examples</b>\n"
    "  /topgainers 1h 10        \u2192 Top 10 gainers last hour\n"
    "  /toplosers 1mo nifty500  \u2192 Monthly losers, NIFTY 500\n"
    "  /topmovers 2d 10 500     \u2192 2-day movers, top 10\n"
    "  /corpactions dividend    \u2192 Upcoming dividends\n"
    "  /myfavourites run        \u2192 All your regular commands in one go\n"
    "  /addstock INFY NSE       \u2192 Add INFY to watchlist\n"
    "\U0001F4DD You can also just type plain text: \"gainers\", \"dividends\", \"news\"."
)
