"""Static help and menu texts shown by the bot (/help, /all, /menu)."""

HELP_TEXT = (
    "\U0001F4CA <b>Stock Alert Bot \u2014 Command Guide</b>\n"
    "<i>Real-time NSE/BSE corporate actions, market movers &amp; news</i>\n\n"
    "Every command name explains what it does. The old short forms still work\n"
    "as aliases (e.g. <code>/ca</code> = <code>/corpactions</code>, "
    "<code>/next</code> = <code>/corpactionsformylist</code>).\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\U0001F3A8 <b>Colour &amp; Signal Legend</b>\n"
    "\U0001F7E2\u25b2 Green + Up arrow = Stock gaining\n"
    "\U0001F534\u25bc Red + Down arrow  = Stock falling\n"
    "\u2705 <b>Strong Buy</b> = Near 52-week LOW (\u226415% from bottom)\n"
    "\U0001F4C8 <b>Buy Zone</b>  = Low zone (15\u201335% from bottom)\n"
    "\U0001F7E1 <b>Mid-Range</b> = Middle of 52-week range\n"
    "\u26a0\ufe0f <b>High Zone</b>  = Near 52-week HIGH (65\u201385%)\n"
    "\U0001F6AB <b>Avoid</b>     = At/near 52-week HIGH (\u226585%)\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\U0001F4C5 <b>Corporate Actions (NSE + BSE)</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/corpactions <i>[TYPE | SYMBOL | N | today]</i>\n"
    "  Browse all dividend / bonus / split / rights / buyback actions.\n"
    "  /corpactions                  \u2192 overview of everything upcoming\n"
    "  /corpactions dividend         \u2192 only dividend announcements\n"
    "  /corpactions bonus|split|rights|buyback  \u2192 one action type\n"
    "  /corpactions increase         \u2192 shareholder increase (bonus+split+rights)\n"
    "  /corpactions today            \u2192 ex-dates due today\n"
    "  /corpactions 7                \u2192 ex-dates within the next 7 days\n"
    "  /corpactions RELIANCE         \u2192 full details for one symbol\n"
    "  /corpactions TATA             \u2192 keyword search (company/subject)\n\n"
    "/exdates <i>[today|N]</i>       \u2192 all actions by ex-date window\n"
    "  (default 5 days) \u00b7  /exdates today  \u00b7  /exdates 10\n\n"
    "/corpactionssummary  \u2192 corporate-action snapshot: counts by exchange\n"
    "                       &amp; type, plus the next ex-dates\n\n"
    "/corpactionsformylist \u2192 YOUR watchlist: upcoming ex-dates PLUS recently\n"
    "                       passed / in-progress actions with status (rights\n"
    "                       subscription open, dividend payment due/pending,\n"
    "                       bonus credit) \u2014 last 30 days\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\u2B50 <b>Watchlist</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/watchlist           \u2192 show your full watchlist\n"
    "/myfavourites        \u2192 see / run / edit your favourite commands:\n"
    "                       <code>/myfavourites run</code> fires them all now\n"
    "/addstock SYMBOL [NSE|BSE] \u2192 add a stock (default NSE)\n"
    "  /addstock RELIANCE NSE  \u00b7  /addstock PGINVIT\n"
    "/removestock SYMBOL  \u2192 remove a stock from your watchlist\n"
    "  /removestock TCS\n"
    "/news <i>[N|SYMBOL]</i> \u2192 latest headlines for your watchlist stocks\n"
    "  /news              \u2192 news for all watchlist stocks\n"
    "  /news 5            \u2192 5 headlines per stock\n"
    "  /news RELIANCE     \u2192 news for RELIANCE only\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\U0001F50D <b>Stock Analysis</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/fundamentalanalyze <i>SYMBOL</i>  \u2192 quick analysis card\n"
    "  /fundamentalanalyze TATATECH  \u2192 price, P/E, 52W signal, QoQ shareholding\n"
    "/fundamentalanalyze <i>N | N-M | mylist</i>  \u2192 same card for your stocks\n"
    "  /fundamentalanalyze mylist  \u2192 your whole watchlist (10 per page, Next button)\n"
    "  /fundamentalanalyze 5-10    \u2192 watchlist stocks #5 to #10\n\n"
    "/fundamentalreport <i>SYMBOL</i>  \u2192 DEEP fundamental report\n"
    "  (much more detailed than /fundamentalanalyze)\n"
    "  /fundamentalreport RELIANCE  \u2192 valuation, growth, margins, balance sheet,\n"
    "                     EPS, analyst targets &amp; shareholding\n"
    "  /fundamentalreport 3-5   \u2192 deep report for watchlist #3..#5\n"
    "  /fundamentalreport mylist \u2192 deep report for your whole watchlist (5 per page)\n\n"
    "/usstock <i>TICKER</i>       \u2192 US stock details (live price + deep fundamentals\n"
    "                     in USD): P/E, fwd P/E, PEG, P/B, P/S, D/E, margins,\n"
    "                     EPS, analyst targets, market cap ($B)...\n"
    "  /usstock AAPL  \u00b7  /usstock MSFT  \u00b7  /usstock NVDA  \u00b7  /usstock BRK-B\n"
    "  Schedule it: <code>/schedule add 3h /usstock AAPL us</code> (US hours only)\n"
    "  Aliases: /usfund \u00b7 /usquote \u00b7 /us\n\n"
    "/checklist <i>SYMBOL</i>  \u2192 32-point investment scorecard\n"
    "  10 personal + 22 AI criteria checked &amp; scored (D/E, ROE, ROCE, margins,\n"
    "  FCF, PEG, P/FCF, EV/EBITDA, P/E vs sector...).\n"
    "  /checklist RELIANCE  \u2192 one stock \u00b7  /checklist mylist \u00b7  /checklist 5-10\n"
    "  (alias /investcheck, /scorecard)\n\n"
    "/harmonicpatterns <i>[all|100|500] [TIMEFRAME]</i>  \u2192 harmonic patterns\n"
    "  Scans for Gartley / Bat / Butterfly / Crab / Shark setups.\n"
    "  /harmonicpatterns all  \u2192 NIFTY 100, daily \u00b7  /harmonicpatterns 500 1w\n"
    "  /harmonicpatterns RELIANCE  \u2192 full report with PRZ, entry, SL &amp; targets\n"
    "  Timeframes: 5m 15m 30m 1h 4h 1d 1w (alias /harmonic)\n\n"
    "/scan500             \u2192 full NIFTY 500 CNC/MIS technical scanner\n"
    "  EMAs, SMA 50/200, RSI, MACD, Stochastic, Bollinger, CCI, ADX, Aroon,\n"
    "  Parabolic SAR, CMF, MFI, OBV, TTM Squeeze, Supertrend, GMMA, VWAP &amp;\n"
    "  Mansfield RS \u2014 scores survivors /100, then a FULL indicator card for\n"
    "  each of the TOP 10: trend, momentum, volume/flow, entry/SL/targets\n"
    "  (takes ~1-2 min).\n\n"
    "/indicator <i>SYMBOL [INDICATOR]</i>  \u2192 clear deep-dive for ONE indicator\n"
    "  /indicator RELIANCE RSI  \u2192 value, signal, 5-session trend, what it\n"
    "  means and how to read the levels \u00b7  /indicator AAPL MACD (US works)\n"
    "  /indicator RELIANCE      \u2192 the FULL all-indicators card\n"
    "  Indicators: rsi \u00b7 macd \u00b7 stochastic \u00b7 bollinger \u00b7 cci \u00b7 adx \u00b7 aroon \u00b7\n"
    "  psar \u00b7 supertrend \u00b7 ema/sma \u00b7 gmma \u00b7 vwap \u00b7 atr \u00b7 donchian \u00b7\n"
    "  squeeze \u00b7 cmf \u00b7 mfi \u00b7 obv \u00b7 (aliases /ind, /tech, /technical)\n\n"
    "/forecast <i>SYMBOL</i>   \u2192 the forecast value for a stock\n"
    "  /forecast RELIANCE  \u2192 analyst consensus &amp; rating breakdown, the\n"
    "  12-month target price with upside, the top executives &amp; (NSE) top\n"
    "  competitors by market cap \u00b7  /forecast AAPL (US works too)\n"
    "  (aliases /analyst, /forecastanalysis)\n\n"
    "/learn <i>[TOPIC | /COMMAND | all]</i>  \u2192 the detailed guide to EVERY command\n"
    "  /learn stocks          \u2192 walk through fundamental analysis\n"
    "  /learn schedule        \u2192 walk through automation &amp; scheduling\n"
    "  /learn /scan500        \u2192 full walkthrough of one command\n"
    "  /learn all             \u2192 the entire guide (aliases /guide, /explain)\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\U0001F4C8 <b>Market Screens</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/topmovers <i>[period|DATE] [N] [100|500]</i>  \u2192 top gainers AND losers\n"
    "  /topmovers          \u2192 last 1h, NIFTY 100\n"
    "  /topmovers 2d 500   \u2192 2-day movers, NIFTY 500\n"
    "  /topmovers 1w 10    \u2192 top 10 movers this week\n"
    "  /topmovers 12-08-2026  \u2192 that day\u2019s HISTORICAL movers (any date)\n\n"
    "/moversover <i>[%] [100|500|sp500]</i>  \u2192 ALL stocks that moved over a % today, one list\n"
    "  /moversover          \u2192 every stock up/down \u2265 5% today, NIFTY 500\n"
    "  /moversover 8        \u2192 \u2265 8% session move\n"
    "  /moversover 8 sp500  \u2192 S&P 500 (aliases /bigmovers, /bigmover, /moverlist, /watcherlist)\n"
    "  Runs only during market hours + 1h after close - IST for NIFTY,\n"
    "  ET for S&P 500 / NASDAQ 100 - so stale session moves are never shown.\n\n"
    "/topgainers <i>[period|DATE] [N] [100|500]</i>  \u2192 top rising stocks\n"
    "  /topgainers 1h          \u2192 last 1h gainers\n"
    "  /topgainers 1mo 20 500  \u2192 top 20 gainers this month, NIFTY 500\n"
    "  /topgainers 12-08-2026  \u2192 that day\u2019s HISTORICAL gainers (any date)\n\n"
    "/toplosers <i>[period] [N] [100|500]</i>  \u2192 top falling stocks\n"
    "  Tap any line below to copy the command:\n"
    "  <code>/toplosers</code>              \u2192 today\u2019s top 30 losers\n"
    "  <code>/toplosers 1h 10</code>        \u2192 top 10 losers last hour\n"
    "  <code>/toplosers 100</code>          \u2192 top 100 losers today\n"
    "  <code>/toplosers 1w nifty100</code>  \u2192 weekly losers, NIFTY 100\n"
    "  <code>/toplosers 20 500</code>       \u2192 top 20 losers, NIFTY 500\n"
    "  <code>/toplosers 30m</code>          \u2192 last 30 minutes\n"
    "  <code>/toplosers 12-08-2026</code>   \u2192 that day\u2019s HISTORICAL losers (any date)\n"
    "  Type /toplosers alone for the full copy-paste guide.\n"
    "  Movers reports end with a <b>Get Fundamentals</b> button - tap it for\n"
    "  P/E, ROCE/ROE, dividend yield etc. Change this with /fundmode.\n\n"
    "Periods: 5m \u00b7 15m \u00b7 30m \u00b7 1h \u00b7 2h \u00b7 4h \u00b7 today \u00b7 1d \u00b7 2d \u00b7 5d \u00b7 1w \u00b7 2w \u00b7 1mo \u00b7 3mo \u00b7 6mo \u00b7 1y\n"
    "Dates: any of the above commands also takes a DATE (12-08-2026, 12 Aug, 12aug,\n"
    "2026-08-12) for that day\u2019s historical movers - e.g. /toplosers 12-08-2026.\n"
    "Market-hours gate: live screens (no DATE) run only during trading hours +\n"
    "1h after close - IST for NIFTY, ET for S&P 500 / NASDAQ 100. Date queries\n"
    "are exempt and work any time.\n"
    "Universe: n100/nifty100=NIFTY 100 \u00b7 n500/nifty500=NIFTY 500\n"
    "Tip: for /topgainers &amp; /toplosers a bare 100/500 means the top-N count\n"
    "(e.g. /topgainers 100 = top 100) - use nifty100/nifty500 or a second\n"
    "number for the index. For /topmovers a bare 100/500 picks the index.\n\n"
    "/gappers <i>[1d|2d|3d|window Nd|DATE|DATE DATE] [up|down|all] [N] [100|500|sp500]</i>\n"
    "  \u2192 overnight gap scanner: shows the gap between a PREVIOUS close and\n"
    "  an OPEN (what /topgainers &amp; /toplosers don't show), plus the move\n"
    "  since the open. Default = gap-DOWNs only.\n"
    "  <code>/gappers</code>            \u2192 top 15 gap-downs today, NIFTY 500\n"
    "  <code>/gappers up</code> / <code>all</code>  \u2192 gap-ups only / both\n"
    "  <code>/gappers 1d</code> / <code>2d</code> / <code>3d</code>  \u2192 gaps that opened 1/2/3 sessions ago\n"
    "  <code>/gappers window 3d</code>  \u2192 today's open vs the close 3 sessions ago\n"
    "  <code>/gappers 12-08-2026</code>  \u2192 the gaps that opened ON that date\n"
    "  <code>/gappers 08-08-2026 12-08-2026</code>  \u2192 cumulative gap over a period\n"
    "    (open on the end date vs the close before the start date)\n"
    "  Dates also work as 12 Aug, 12aug, aug12, 2026-08-12\n"
    "  <code>/gappers sp500</code>     \u2192 S&P 500 \u00b7 <code>/gappers 20 nifty100</code>\n"
    "  <code>/gappers GODREJCP</code>  \u2192 that stock's recent gap history\n"
    "  (each session's close \u2192 next session's open)\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\u2699\ufe0f <b>Alerts &amp; Personalisation</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/alertfilters        \u2192 corporate-action alert switch + type filter\n"
    "  /alertfilters off             \u2192 SILENCE all corporate-action alerts\n"
    "  /alertfilters dividend,bonus  \u2192 only those types \u00b7  /alertfilters all (reset)\n"
    "  Types: dividend \u00b7 bonus \u00b7 split \u00b7 rights \u00b7 buyback\n"
    "/corpactions on|off  \u2192 same switch, on the corporate-actions command\n"
    "/pricealert PCT      \u2192 alert when a stock moves \u00b1PCT% in a day\n"
    "  /pricealert 3      \u2192 alert on \u00b13% move  \u00b7  /pricealert off (disable)\n"
    "  /pricealert on     \u2192 re-enable the last threshold\n"
    "/quiet               \u2192 master pause: mute ALL automatic messages\n"
    "  /quiet on  \u00b7  /quiet 2h (timed)  \u00b7  /quiet off (resume) - commands still work\n"
    "/settings            \u2192 view your current filter &amp; alert config\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\U0001F6E0 <b>System</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/status              \u2192 YOUR personal setup (watchlist, schedule, settings, alerts)\n"
    "/schedule add 3h /scan500  \u2192 YOUR report runs /scan500 automatically every 3h\n"
    "  (runs only while the Indian market is open by default - add <code>us</code> for US hours,\n"
    "   <code>any</code> to disable, or <code>from HH:MM to HH:MM</code> for a custom window)\n"
    "/schedule add at 09:15 /toplosers 1h  \u2192 daily at a clock time (09:15 IST;\n"
    "   use <code>us</code> for ET: <code>/schedule add at 09:30 3h /cmd us</code> = every 3h from 09:30 ET)\n"
    "/schedule add at 09:15,15:30 /toplosers 1h  \u2192 daily at BOTH times - start + end\n"
    "   results; a run window (from 09:15 to 15:30) also fires at its start AND end\n"
    "   INTERVAL entries (every 3h) fire EXACTLY on the hour (09:15, 10:15...) plus\n"
    "   once more at session close (15:30 IST / 16:00 ET); clock times you choose\n"
    "   (at 09:15) fire ONLY at those times - no extra close run\n"
    "/schedule pause 1d \u00b7 2d \u00b7 3d \u00b7 1w \u00b7 2w \u00b7 1mo  \u2192 pause YOUR schedule\n"
    "  (auto-resumes when the pause lapses - resume early with /schedule resume)\n"
    "/schedule resume          \u2192 resume early  \u00b7  /market us|in|any  \u2192 default gate\n"
    "/schedule run \u00b7 /schednow  \u2192 run all YOUR scheduled reports right now\n"
    "/checknow            \u2192 force-run alerts and re-send all matches\n"
    "/watcher             \u2192 big-move alerts: /watcher on, off, set 5, universe nifty500\n"
    "/fundmode            \u2192 movers: fundamentals via button or automatically\n"
    "/menu                \u2192 one-tap command buttons (tap, no typing)\n"
    "/all                 \u2192 every command in one copyable list\n"
    "/learn               \u2192 detailed guide: /learn /scan500, /learn schedule\n"
    "/help \u00b7 /start       \u2192 show this guide\n\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "\U0001F4A1 <b>Quick Examples</b>\n"
    "━━━━━━━━━━━━━━━━━━━━\n"
    "/topgainers 1h 10          \u2192 Top 10 gainers last hour\n"
    "/toplosers 1mo nifty500   \u2192 Monthly losers \u2014 NIFTY 500\n"
    "/gappers down             \u2192 Stocks that gapped down at today's open\n"
    "/topmovers 2d 10 500       \u2192 2-day movers, top 10, NIFTY 500\n"
    "/scan500               \u2192 full NIFTY 500 CNC/MIS technical scan\n"
    "/corpactions dividend   \u2192 Upcoming dividends\n"
    "/corpactions RELIANCE   \u2192 RELIANCE corporate actions\n"
    "/corpactionsformylist  \u2192 Watchlist ex-dates + in-progress actions\n"
    "/myfavourites run        \u2192 All your regular commands in one go\n"
    "/addstock INFY NSE      \u2192 Add INFY to watchlist\n"
    "/news RELIANCE          \u2192 Latest RELIANCE headlines\n"
    "/alertfilters bonus,split  \u2192 Only bonus &amp; split alerts\n"
    "/pricealert 2.5         \u2192 Alert on \u00b12.5% daily move\n"
    "\U0001F4DD Type in plain text: \"gainers\", \"dividends\", \"ex-date today\", \"news\""
)

CA_HELP = (
    "Corporate Action queries (/corpactions, alias /ca):\n"
    "/corpactions - overview of all NSE + BSE actions\n"
    "/corpactions dividend | bonus | split | rights | buyback - one action type\n"
    "/corpactions increase - shareholder increase (bonus + split + rights)\n"
    "/corpactions today - ex-date today\n"
    "/corpactions 7 - ex-date within 7 days\n"
    "/corpactions RELIANCE - details for one symbol\n"
    "/corpactions TATA - keyword search in company name / subject\n\n"
    "Corporate-action ALERTS (the automatic pushes to your chat):\n"
    "/corpactions off - turn OFF the automatic corporate-action alerts\n"
    "/corpactions on  - turn them back ON\n"
    "(same switch: /alertfilters off | on | all)"
)

QUICK_MENU_TEXT = (
    "<b>\U0001F447 One-Tap Command Menu</b>\n"
    "Tap any button below - the command runs instantly, no typing needed.\n\n"
    "\u2022 <code>/corpactionsformylist</code> - corporate actions for YOUR list\n"
    "\u2022 <code>/myfavourites run</code> - all your regular commands in one go\n"
    "\u2022 <code>/corpactions</code> - all NSE+BSE corporate actions\n"
    "\u2022 <code>/corpactionssummary</code> - counts + next ex-dates\n"
    "\u2022 <code>/topgainers 1h</code> / <code>/toplosers 1h</code> - movers\n"
    "\u2022 <code>/watchlist</code> - your stocks\n"
    "\u2022 <code>/all</code> - copy the full list of every command\n\n"
    "The menu stays visible until you hide it with <code>/menu off</code>."
)

ALL_COMMANDS_TEXT = (
    "<b>\U0001F4DA All Commands - copy any line and send it</b>\n"
    "<i>Every command you can use, grouped by purpose.</i>\n\n"
    "\u2B50 <b>One-Tap Menu</b>\n"
    "  /menu                    \u2192 show the button menu (always on until /menu off)\n"
    "  /menu off                \u2192 hide the button menu\n"
    "  /all                     \u2192 this list, always up to date\n\n"
    "\U0001F4C5 <b>Corporate Actions</b>\n"
    "  /corpactionsformylist    \u2192 corporate actions for YOUR watchlist\n"
    "  /corpactions             \u2192 all NSE+BSE corporate actions\n"
    "  /corpactionssummary      \u2192 counts + next ex-dates\n"
    "  /corpactions dividend    \u2192 only dividends\n"
    "  /corpactions bonus|split|rights|buyback \u2192 one type\n"
    "  /corpactions today       \u2192 ex-dates due today\n"
    "  /corpactions 7           \u2192 ex-dates in the next 7 days\n"
    "  /corpactions RELIANCE    \u2192 full details for one symbol\n"
    "  /corpactions TATA        \u2192 keyword search\n"
    "  /exdates [today|N]       \u2192 all actions by ex-date window\n\n"
    "\u2B50 <b>Watchlist &amp; Favourites</b>\n"
    "  /watchlist               \u2192 show your watchlist\n"
    "  /myfavourites            \u2192 see the commands it runs\n"
    "  /myfavourites run        \u2192 run your favourite commands\n"
    "  /myfavourites set /cmd   \u2192 replace your favourite commands\n"
    "  /myfavourites add /cmd   \u2192 append a command\n"
    "  /myfavourites remove N   \u2192 remove command #N\n"
    "  /myfavourites reset      \u2192 restore the default list\n"
    "  /addstock SYMBOL NSE|BSE \u2192 add a stock\n"
    "  /removestock SYMBOL      \u2192 remove a stock\n"
    "  /news [N|SYMBOL]         \u2192 headlines for your stocks\n\n"
    "\U0001F50D <b>Stock Analysis</b>\n"
    "  /fundamentalanalyze SYM  \u2192 quick analysis card\n"
    "  /fundamentalanalyze mylist | N-M \u2192 your stocks\n"
    "  /fundamentalreport SYM   \u2192 DEEP fundamental report\n"
    "  /fundamentalreport mylist|N-M \u2192 deep reports for your stocks\n"
    "  /usstock SYM             \u2192 US stock details (USD): /usstock AAPL\n"
    "  /checklist SYM           \u2192 32-point investment scorecard (10 personal + 22 AI)\n"
    "  /checklist mylist | N-M  \u2192 scorecards for your stocks\n"
    "  /harmonicpatterns [100|500] [TF] \u2192 harmonic scan\n"
    "  /indicator SYM [NAME]    \u2192 one-indicator deep-dive (e.g. /indicator RELIANCE RSI)\n"
    "  /indicator SYM           \u2192 full all-indicators card\n"
    "  /forecast SYM            \u2192 analyst forecast, top executives &amp; competitors\n"
    "  /scan500                 \u2192 full NIFTY 500 technical scanner\n\n"
    "\U0001F4C8 <b>Market Screens</b>\n"
    "  /topmovers [period] [N] [100|500]  \u2192 gainers AND losers\n"
    "  /topgainers [period] [N] [100|500] \u2192 top rising stocks\n"
    "  /toplosers [period] [N] [100|500]  \u2192 top falling stocks\n"
    "  /moversover [%] [100|500|sp500]    \u2192 EVERY stock that moved over a % today\n"
    "    /moversover 8 sp500  \u2192 over 8% on the S&P 500 (alias /bigmovers)\n"
    "  /gappers [1d|2d|3d|window Nd|DATE] [up|down|all] [N] [100|500|sp500] \u2192 overnight gaps\n"
    "  /gappers               \u2192 top gap-downs today (default) \u00b7 /gappers up \u2192 gap-ups\n"
    "  /gappers 1d | 2d | 3d  \u2192 gaps N sessions ago \u00b7 /gappers window 3d \u2192 open vs close N ago\n"
    "  /gappers 12-08-2026    \u2192 gaps that opened on that date\n"
    "  /gappers 08-08-2026 12-08-2026 \u2192 cumulative gap over a period\n"
    "  /gappers GODREJCP      \u2192 that stock's recent gap history\n"
    "  /toplosers 12-08-2026  \u2192 that day's historical losers (dates work on all movers)\n"
    "  Copy-ready examples (tap to copy):\n"
    "    <code>/toplosers</code> \u00b7 <code>/toplosers 1h 10</code> \u00b7 "
    "<code>/toplosers 100</code>\n"
    "    <code>/toplosers 1w nifty100</code> \u00b7 <code>/toplosers 20 500</code>\n"
    "  Periods: 5m 15m 30m 1h 2h 4h today 1d 2d 5d 1w 2w 1mo 3mo 6mo 1y\n"
    "  Dates: 12-08-2026 \u00b7 12 Aug \u00b7 12aug \u00b7 2026-08-12 (historical day)\n"
    "  Universe: n100/nifty100 \u00b7 n500/nifty500\n\n"
    "\u2699\ufe0f <b>Alerts &amp; Personalisation</b>\n"
    "  /alertfilters off|on|all  \u2192 corporate-action alerts: silence / re-enable / all types\n"
    "  /alertfilters TYPE,TYPE   \u2192 only chosen action types (dividend,bonus,split,rights,buyback)\n"
    "  /corpactions on|off       \u2192 same corporate-action alert switch\n"
    "  /pricealert PCT|off|on    \u2192 alert on \u00b1PCT% daily move\n"
    "  /watcher on|off|set N|universe U \u2192 big-move alerts\n"
    "  /fundmode button|auto  \u2192 movers reports: fundamentals via button or auto\n"
    "  /quiet on|2h|off       \u2192 master pause: mute ALL automatic messages (commands still work)\n"
    "  /settings                \u2192 view your filters, alerts &amp; screen options\n\n"
    "\U0001F6E0 <b>Automation</b>\n"
    "  /schedule                \u2192 show YOUR schedule\n"
    "  /schedule add 3h /scan500 \u2192 run every 3h\n"
    "  /schedule add at 09:15 /toplosers 1h \u2192 run daily at 09:15 IST\n"
    "  /schedule add at 09:15,15:30 /toplosers 1h \u2192 daily at BOTH (open + close)\n"
    "  /schedule add 3h /scan500 us \u2192 only during US market hours\n"
    "  /schedule add 3h /scan500 any \u2192 no gate - run any time\n"
    "  /schedule add 3h /cmd in from 09:15 to 15:30 \u2192 custom run window (fires at its start AND end)\n"
    "  /schedule add 3h /cmd in|us \u2192 exact hourly (09:15, 10:15...) + a final run at session close (15:30 IST / 16:00 ET)\n"
    "  /schedule add at 09:15 /gappers today \u2192 daily at 09:15 ONLY (chosen times fire exactly)\n"
    "  /schedule pause 1d|2d|3d|1w|2w|1mo \u2192 pause YOUR schedule (auto-resumes)\n"
    "  /schedule resume        \u2192 resume early\n"
    "  /market in|us|any       \u2192 YOUR default market-hours gate\n"
    "  /schedule run           \u2192 run all your scheduled commands NOW\n"
    "  /schednow                \u2192 alias of /schedule run\n"
    "  /schedule remove N       \u2192 remove entry #N\n"
    "  /schedule clear          \u2192 remove all of yours\n"
    "  /checknow                \u2192 force-run alert checks now\n"
    "  /status                  \u2192 your personal setup + GitHub push status\n\n"
    "\U0001F4A1 <b>Quick Examples</b>\n"
    "  /topgainers 1h 10        \u2192 Top 10 gainers last hour\n"
    "  /toplosers 1mo nifty500  \u2192 Monthly losers, NIFTY 500\n"
    "  /topmovers 2d 10 500     \u2192 2-day movers, top 10\n"
    "  /corpactions dividend    \u2192 Upcoming dividends\n"
    "  /myfavourites run        \u2192 All your regular commands in one go\n"
    "  /addstock INFY NSE       \u2192 Add INFY to watchlist\n"
    "\U0001F4DD You can also just type plain text: \"gainers\", \"dividends\", \"news\"."
)
